site_name: Postmanager
site_url: https://postmanager.com/

nav:
  - Home:
      - Overview: index.md
      - Contributing: contributing.md
      - License: license.md
      - Code of Conduct: code_of_conduct.md
      - Changelog: changelog.md

  - Usage:
      - Configuration: usage/configuration.md
      - Examples: usage/examples.md

  - Code Reference:
      - PostManager: code/manager.md
      - Post: code/post.md
      - MediaData: code/media_data.md
      - MetaData: code/meta_data.md
      - StorageProxyLocal: code/storage_proxy_local.md
      - StorageProxyS3: code/storage_proxy_s3.md
      - StorageAdapter: code/storage_adapter.md

  - Author's website: https://pierredutoit.me

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - css/style.css
  - css/material.css
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - toc:
      permalink: "«"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: false
          selection:
            docstring_style: google

      watch:
        - src/postmanager
        - ./README.md

extra:
  generator: false
