name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: True

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
        # include:
        #   - os: windows-latest
        #     python-version: "3.7"
        #   - os: macos-latest
        #     python-version: "3.7"

    steps:
      - name: Check out code repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install -r requirements.txt
          pip install -e .

      - name: Run Pytest
        run: python -m pytest discover
